//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TKDbContext : DbContext
    {
        public TKDbContext()
            : base("name=TKDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<chinhanh> chinhanhs { get; set; }
        public virtual DbSet<dmdaily> dmdailies { get; set; }
        public virtual DbSet<doanhthuDoanNgayDi> doanhthuDoanNgayDis { get; set; }
        public virtual DbSet<doanhthuQuayChitiet> doanhthuQuayChitiets { get; set; }
        public virtual DbSet<doanhthuSaleQuay> doanhthuSaleQuays { get; set; }
        public virtual DbSet<doanhthuToanhethong> doanhthuToanhethongs { get; set; }
        public virtual DbSet<doanthuQuayNgayBan> doanthuQuayNgayBans { get; set; }
        public virtual DbSet<tuyentqNgaydi> tuyentqNgaydis { get; set; }
        public virtual DbSet<thongkeweb> thongkewebs { get; set; }
        public virtual DbSet<doanhthuSaleChitiet> doanhthuSaleChitiets { get; set; }
        public virtual DbSet<doanhthuDoanChitiet> doanhthuDoanChitiets { get; set; }
        public virtual DbSet<chitiettour> chitiettours { get; set; }
        public virtual DbSet<thongkewebchitiet> thongkewebchitiets { get; set; }
        public virtual DbSet<doanhthuSaleTuyen> doanhthuSaleTuyens { get; set; }
        public virtual DbSet<doanhthuSaleTuyentqChitiet> doanhthuSaleTuyentqChitiets { get; set; }
        public virtual DbSet<tuyentheoquy> tuyentheoquys { get; set; }
        public virtual DbSet<QuayNgayBan> QuayNgayBans { get; set; }
        public virtual DbSet<KhachHuy> KhachHuys { get; set; }
        public virtual DbSet<TuyentqChiTiet> TuyentqChiTiets { get; set; }
    
        public virtual ObjectResult<doanhthuDoanNgayDi> spBaocaoDoanhThuDoanTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuDoanNgayDi>("spBaocaoDoanhThuDoanTheoNgayDi", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuDoanNgayDi> spBaocaoDoanhThuDoanTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuDoanNgayDi>("spBaocaoDoanhThuDoanTheoNgayDi", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanthuQuayNgayBan> spBaocaoDoanhThuQuayTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanthuQuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayDi", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanthuQuayNgayBan> spBaocaoDoanhThuQuayTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanthuQuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayDi", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleQuay> spBaocaoDoanhThuSaleTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleQuay>("spBaocaoDoanhThuSaleTheoNgayDi", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleQuay> spBaocaoDoanhThuSaleTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleQuay>("spBaocaoDoanhThuSaleTheoNgayDi", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleQuay> spBaocaoDoanhThuSaleTheoQuay(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleQuay>("spBaocaoDoanhThuSaleTheoQuay", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleQuay> spBaocaoDoanhThuSaleTheoQuay(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleQuay>("spBaocaoDoanhThuSaleTheoQuay", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuQuayChitiet> spDoanhSoQuayChitietNgayBan(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string quay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var quayParameter = quay != null ?
                new ObjectParameter("quay", quay) :
                new ObjectParameter("quay", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuQuayChitiet>("spDoanhSoQuayChitietNgayBan", tungayParameter, denngayParameter, quayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuQuayChitiet> spDoanhSoQuayChitietNgayBan(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string quay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var quayParameter = quay != null ?
                new ObjectParameter("quay", quay) :
                new ObjectParameter("quay", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuQuayChitiet>("spDoanhSoQuayChitietNgayBan", mergeOption, tungayParameter, denngayParameter, quayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleChitiet> spDoanhThuSaleChitietNgayban(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string nhanvien, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var nhanvienParameter = nhanvien != null ?
                new ObjectParameter("nhanvien", nhanvien) :
                new ObjectParameter("nhanvien", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleChitiet>("spDoanhThuSaleChitietNgayban", tungayParameter, denngayParameter, nhanvienParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleChitiet> spDoanhThuSaleChitietNgayban(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string nhanvien, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var nhanvienParameter = nhanvien != null ?
                new ObjectParameter("nhanvien", nhanvien) :
                new ObjectParameter("nhanvien", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleChitiet>("spDoanhThuSaleChitietNgayban", mergeOption, tungayParameter, denngayParameter, nhanvienParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleChitiet> spDoanhThuSaleChitietNgaydi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string nhanvien, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var nhanvienParameter = nhanvien != null ?
                new ObjectParameter("nhanvien", nhanvien) :
                new ObjectParameter("nhanvien", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleChitiet>("spDoanhThuSaleChitietNgaydi", tungayParameter, denngayParameter, nhanvienParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleChitiet> spDoanhThuSaleChitietNgaydi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string nhanvien, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var nhanvienParameter = nhanvien != null ?
                new ObjectParameter("nhanvien", nhanvien) :
                new ObjectParameter("nhanvien", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleChitiet>("spDoanhThuSaleChitietNgaydi", mergeOption, tungayParameter, denngayParameter, nhanvienParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual int spThongKeDoanhthu(string khoi)
        {
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThongKeDoanhthu", khoiParameter);
        }
    
        public virtual int spThongkeKhach(string khoi)
        {
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spThongkeKhach", khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuToanhethong> spThongkeKhachToanHeThong(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuToanhethong>("spThongkeKhachToanHeThong", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuToanhethong> spThongkeKhachToanHeThong(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuToanhethong>("spThongkeKhachToanHeThong", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<tuyentqNgaydi> spThongkeTuyentqTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tuyentqNgaydi>("spThongkeTuyentqTheoNgayDi", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<tuyentqNgaydi> spThongkeTuyentqTheoNgayDi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tuyentqNgaydi>("spThongkeTuyentqTheoNgayDi", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuQuayChitiet> spDoanhSoQuayChitietNgaydi(string quay, string chinhanh, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string khoi)
        {
            var quayParameter = quay != null ?
                new ObjectParameter("quay", quay) :
                new ObjectParameter("quay", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuQuayChitiet>("spDoanhSoQuayChitietNgaydi", quayParameter, chinhanhParameter, tungayParameter, denngayParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuQuayChitiet> spDoanhSoQuayChitietNgaydi(string quay, string chinhanh, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string khoi, MergeOption mergeOption)
        {
            var quayParameter = quay != null ?
                new ObjectParameter("quay", quay) :
                new ObjectParameter("quay", typeof(string));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuQuayChitiet>("spDoanhSoQuayChitietNgaydi", mergeOption, quayParameter, chinhanhParameter, tungayParameter, denngayParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkeweb> spThongkeWeb(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkeweb>("spThongkeWeb", tungayParameter, denngayParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkeweb> spThongkeWeb(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkeweb>("spThongkeWeb", mergeOption, tungayParameter, denngayParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkewebchitiet> spThongkeWebchitiet(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkewebchitiet>("spThongkeWebchitiet", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkewebchitiet> spThongkeWebchitiet(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkewebchitiet>("spThongkeWebchitiet", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuDoanChitiet> spDoanhthuDoanChitiet(string sgtcode, string khoi)
        {
            var sgtcodeParameter = sgtcode != null ?
                new ObjectParameter("sgtcode", sgtcode) :
                new ObjectParameter("sgtcode", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuDoanChitiet>("spDoanhthuDoanChitiet", sgtcodeParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuDoanChitiet> spDoanhthuDoanChitiet(string sgtcode, string khoi, MergeOption mergeOption)
        {
            var sgtcodeParameter = sgtcode != null ?
                new ObjectParameter("sgtcode", sgtcode) :
                new ObjectParameter("sgtcode", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuDoanChitiet>("spDoanhthuDoanChitiet", mergeOption, sgtcodeParameter, khoiParameter);
        }
    
        public virtual ObjectResult<spGetTourByCode_Result> spGetTourByCode(string sgtcode, string khoi)
        {
            var sgtcodeParameter = sgtcode != null ?
                new ObjectParameter("sgtcode", sgtcode) :
                new ObjectParameter("sgtcode", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetTourByCode_Result>("spGetTourByCode", sgtcodeParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkeweb> spThongkeWeb_ngaydi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkeweb>("spThongkeWeb_ngaydi", tungayParameter, denngayParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkeweb> spThongkeWeb_ngaydi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkeweb>("spThongkeWeb_ngaydi", mergeOption, tungayParameter, denngayParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkewebchitiet> spThongkeWebchitiet_ngaydi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkewebchitiet>("spThongkeWebchitiet_ngaydi", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<thongkewebchitiet> spThongkeWebchitiet_ngaydi(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<thongkewebchitiet>("spThongkeWebchitiet_ngaydi", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleTuyen> spBaocaoDoanhThuSaleTheoTuyen(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string tuyentq, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var tuyentqParameter = tuyentq != null ?
                new ObjectParameter("tuyentq", tuyentq) :
                new ObjectParameter("tuyentq", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleTuyen>("spBaocaoDoanhThuSaleTheoTuyen", tungayParameter, denngayParameter, tuyentqParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleTuyen> spBaocaoDoanhThuSaleTheoTuyen(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string tuyentq, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var tuyentqParameter = tuyentq != null ?
                new ObjectParameter("tuyentq", tuyentq) :
                new ObjectParameter("tuyentq", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleTuyen>("spBaocaoDoanhThuSaleTheoTuyen", mergeOption, tungayParameter, denngayParameter, tuyentqParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleTuyentqChitiet> spDoanhThuSaleChitietTuyentq(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string nhanvien, string tuyentq, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var nhanvienParameter = nhanvien != null ?
                new ObjectParameter("nhanvien", nhanvien) :
                new ObjectParameter("nhanvien", typeof(string));
    
            var tuyentqParameter = tuyentq != null ?
                new ObjectParameter("tuyentq", tuyentq) :
                new ObjectParameter("tuyentq", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleTuyentqChitiet>("spDoanhThuSaleChitietTuyentq", tungayParameter, denngayParameter, nhanvienParameter, tuyentqParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanhthuSaleTuyentqChitiet> spDoanhThuSaleChitietTuyentq(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string nhanvien, string tuyentq, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var nhanvienParameter = nhanvien != null ?
                new ObjectParameter("nhanvien", nhanvien) :
                new ObjectParameter("nhanvien", typeof(string));
    
            var tuyentqParameter = tuyentq != null ?
                new ObjectParameter("tuyentq", tuyentq) :
                new ObjectParameter("tuyentq", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanhthuSaleTuyentqChitiet>("spDoanhThuSaleChitietTuyentq", mergeOption, tungayParameter, denngayParameter, nhanvienParameter, tuyentqParameter, khoiParameter);
        }
    
        public virtual ObjectResult<spDoanthuQuayTungay_Dengay_Result> spDoanthuQuayTungay_Dengay(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string vanphong, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var vanphongParameter = vanphong != null ?
                new ObjectParameter("vanphong", vanphong) :
                new ObjectParameter("vanphong", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDoanthuQuayTungay_Dengay_Result>("spDoanthuQuayTungay_Dengay", tungayParameter, denngayParameter, vanphongParameter, khoiParameter);
        }
    
        public virtual ObjectResult<string> spLoadTuyentq(string khoi)
        {
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spLoadTuyentq", khoiParameter);
        }
    
        public virtual ObjectResult<tuyentheoquy> spThongkeTuyenTheoQuy(Nullable<int> quy, Nullable<int> nam, string chinhanh, string khoi)
        {
            var quyParameter = quy.HasValue ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tuyentheoquy>("spThongkeTuyenTheoQuy", quyParameter, namParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<tuyentheoquy> spThongkeTuyenTheoQuy(Nullable<int> quy, Nullable<int> nam, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var quyParameter = quy.HasValue ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tuyentheoquy>("spThongkeTuyenTheoQuy", mergeOption, quyParameter, namParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<QuayNgayBan> spBaocaoDoanhThuQuayTheoNgayBan(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayBan", tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<QuayNgayBan> spBaocaoDoanhThuQuayTheoNgayBan(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, string khoi, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            var khoiParameter = khoi != null ?
                new ObjectParameter("khoi", khoi) :
                new ObjectParameter("khoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayBan", mergeOption, tungayParameter, denngayParameter, chinhanhParameter, khoiParameter);
        }
    
        public virtual ObjectResult<doanthuQuayNgayBan> spBaocaoDoanhThuQuayTheoNgayBanND(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanthuQuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayBanND", tungayParameter, denngayParameter, chinhanhParameter);
        }
    
        public virtual ObjectResult<doanthuQuayNgayBan> spBaocaoDoanhThuQuayTheoNgayBanND(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanthuQuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayBanND", mergeOption, tungayParameter, denngayParameter, chinhanhParameter);
        }
    
        public virtual ObjectResult<doanthuQuayNgayBan> spBaocaoDoanhThuQuayTheoNgayBanOB(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanthuQuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayBanOB", tungayParameter, denngayParameter, chinhanhParameter);
        }
    
        public virtual ObjectResult<doanthuQuayNgayBan> spBaocaoDoanhThuQuayTheoNgayBanOB(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay, string chinhanh, MergeOption mergeOption)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            var chinhanhParameter = chinhanh != null ?
                new ObjectParameter("chinhanh", chinhanh) :
                new ObjectParameter("chinhanh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doanthuQuayNgayBan>("spBaocaoDoanhThuQuayTheoNgayBanOB", mergeOption, tungayParameter, denngayParameter, chinhanhParameter);
        }
    }
}
