//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThongKe.Data.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuyentheoquy
    {
        public long stt { get; set; }
        public string tuyentq { get; set; }
        public Nullable<int> sk1 { get; set; }
        public Nullable<decimal> doanhso1 { get; set; }
        public Nullable<int> sk_1 { get; set; }
        public Nullable<decimal> doanhso_1 { get; set; }
        public Nullable<int> sk2 { get; set; }
        public Nullable<decimal> doanhso2 { get; set; }
        public Nullable<int> sk_2 { get; set; }
        public Nullable<decimal> doanhso_2 { get; set; }
        public Nullable<int> sk3 { get; set; }
        public Nullable<decimal> doanhso3 { get; set; }
        public Nullable<int> sk_3 { get; set; }
        public Nullable<decimal> doanhso_3 { get; set; }
    }
}
